vim.g.mapleader = " "
vim.g.maplocalleader = " "
vim.g.clipboard = unnamedplus 
vim.opt.number = true
vim.opt.relativenumber = false 
vim.opt.autoindent = true 
vim.opt.tabstop = 4
vim.opt.softtabstop = 4
vim.opt.smarttab = true 
vim.opt.showmatch = true 
vim.opt.hlsearch = true 
vim.opt.cursorline = true 
vim.opt.laststatus = 2
vim.opt.wrap = true 
vim.opt.textwidth = 80
vim.opt.termguicolors = true
vim.opt.background = "dark"
vim.cmd.colorscheme "oxocarbon"
vim.cmd[[set encoding=utf-8]]
