require("plugin_config.lualine")
require("plugin_config.nvim-tree")
require("plugin_config.telescope")
require("plugin_config.coc-nvim")
require("plugin_config.nvim-tree-sitter")
-- require("plugin_config.catppuccin")
require("plugin_config.nvim-devicons")
require("plugin_config.bufferline")
require("plugin_config.comment")
require("plugin_config.blankline")
